### ISSUE TITLE
Recognizes waypoints on initialize but not on scroll

### ISSUE THREAD

**Issue by xd0** [imakewebthings/waypoints#493] opened 2016-06-06 10:20 UTC
Hi,

I've got a problem with jQuery Waypoints 4.0.0, everything seems to work fine until i interact with the waypoints. It seems the first waypoint doesn't work.

What I'm trying to achieve is to change the text in navigation depending on where you are at the page and I almost got it working. It works on initialize (it recognizes the first chapter and sets the text from that attribute "data-title") and when I'm scrolling the page it changes text on each chapter except if i scroll to "Chapter 1" again.

Is this a bug or am i doing something wrong?

Here's a jsfiddle:
https://jsfiddle.net/zlitrox/dggc9xxg/2/

**Comment by imakewebthings** [comment] 2016-06-14 16:40
It's not a bug **and** you haven't done anything wrong. I believe you have half of the implementation you need.

>  It seems the first waypoint doesn't work.

I'd argue all of them don't *completely* work. In the screenshot below I've scrolled *almost* to Chapter 2. The sidebar says Chapter 1. So far so good.

![scrolling down](https://cloud.githubusercontent.com/assets/406639/16050933/6ea517ee-3212-11e6-93b3-6c32640a997c.png)

When I scroll past Chapter 2, then scroll back up to the same spot, the sidebar now says Chapter 2.

![scrolling up](https://cloud.githubusercontent.com/assets/406639/16051010/be6c2c40-3212-11e6-81b4-9395a2c1696e.png)

I bet this wasn't intentional. I bet, like most people in the majority of cases, you would like the sidebar to be the same value when at the same scroll position no matter what direction the user was scrolling when they landed there. You have the scrolling down part working fine, now let's handle the scrolling up direction. When we hit a waypoint scrolling up, we'll set the sidebar text to the title of the waypoint *above* it: https://jsfiddle.net/dggc9xxg/4/

With this pattern in place I like to change the offset to a higher percent, something between 10-50%, but that's just personal preference.

**Closed** 2016-06-21 15:04 UTC
