### ISSUE TITLE
No main in package.json

### ISSUE THREAD

**Issue by bl4ckdu5t** [imakewebthings/waypoints#495] opened 2016-06-14 20:38 UTC
Without the main entry in the package.json, the package can't be successfully used through browserify/webpack require. I'd simply just add a main. I considered it may have been skipped because there are different possible main i.e the noframework, zepto, or jQuery builds but when I try to relatively require those. There's no part of the code that exports the module.

**Comment by imakewebthings** [comment] 2016-06-15 15:47
Duplicate of #458. Aware of the problem w/ a roadmap to fix it.

**Closed by imakewebthings** 2016-06-15 15:47 UTC

**Comment by derwaldgeist** [comment] 2018-07-23 22:03
> w/ a roadmap to fix it

When exactly? ;-)
