### ISSUE TITLE
Waypoints disappear on window resize

### ISSUE THREAD

**Issue by peterph-am** [imakewebthings/waypoints#362] opened 2015-01-13 06:54 UTC
I'm using js waypoints to add some classes to a few elements on scroll.

But I've noticed that when I resize the browser window the waypoints sometimes disappear.

Not sure if it's because the elements are fixed before firing waypoints?

I'm using the latest jQuery version of waypoints.

Here's the staging site:
http://staging.peterph.am/dilia

**Comment by imakewebthings** [comment] 2015-01-13 07:25
Have you tried [adding the debug script](http://imakewebthings.com/waypoints/guides/debugging/) and seeing if there are errors?

**Comment by peterph-am** [comment] 2015-01-14 10:21
Yes I have, I don't see any debug errors in the console?

**Comment by imakewebthings** [comment] 2015-01-14 20:31
@peterph-am Cool. Can you include the debug script on that staging site, then let me know on here when you have and I will take a deeper look?

**Comment by peterph-am** [comment] 2015-01-15 21:31
@imakewebthings I've added it to the site now

**Comment by imakewebthings** [comment] 2015-01-15 22:09
@peterph-am This is a bug with my debug script. It isn't catching your fixed position element. I'll issue a fix for that soon and it will be part of the next release.

In the meantime, to summarize, yes the problem is you're using a fixed position element as a Waypoint. You can read about that [here](http://imakewebthings.com/waypoints/guides/debugging/#fixed-position). You need to use an element that stays statically positioned as the waypoint. For example, in the [sticky shortcut](http://imakewebthings.com/waypoints/shortcuts/sticky-elements) a wrapper is created around the element that acts as both a placeholder to prevent content shifting and the statically positioned waypoint.

**Closed by imakewebthings** 2015-01-15 22:09 UTC
